### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by amitkumarnagar** [react-navigation/react-navigation.github.io#1019]
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ws (https://reactnavigation.org/assets/js/main.259f93bb.js:2:387857)
    at ws (https://reactnavigation.org/assets/js/main.259f93bb.js:2:387930)
    at xs (https://reactnavigation.org/assets/js/main.259f93bb.js:2:387368)
    at Ac (https://reactnavigation.org/assets/js/main.259f93bb.js:2:400093)
    at t.unstable_runWithPriority (https://reactnavigation.org/assets/js/main.259f93bb.js:2:447563)
    at Hr (https://reactnavigation.org/assets/js/main.259f93bb.js:2:343592)
    at Oc (https://reactnavigation.org/assets/js/main.259f93bb.js:2:398257)
    at vc (https://reactnavigation.org/assets/js/main.259f93bb.js:2:394368)
    at https://reactnavigation.org/assets/js/main.259f93bb.js:2:343815
    at t.unstable_runWithPriority (https://reactnavigation.org/assets/js/main.259f93bb.js:2:447563)
```
<img width="1440" alt="Screenshot 2021-07-11 at 10 40 47 PM" src="https://user-images.githubusercontent.com/36877629/125204081-0a8fc500-e299-11eb-8850-2cb978bdc9e4.png">

https://user-images.githubusercontent.com/36877629/125203957-83dae800-e298-11eb-99d3-a6f604113f6e.mov

**Comment by eriveltonelias** [comment]
hey there! 

this issue has been already fixed, thanks!
