### ISSUE TITLE
Error: Unable to resolve module `./components/TouchableRipple` from `node_modules\react-native-paper\src\index.tsx

### ISSUE THREAD

**Issue by feliperoan** [react-navigation/react-navigation.github.io#884]
Hello, can someone help me with
I have tried installing modules returning versions but it does not disappear
any ideas ?
"react-native-paper": "^4.0.1",
"react-native-safe-area-context": "^3.1.4",
"react-native-screens": "^2.10.1", "react-native-reanimated": "^1.13.0",
"@react-native-community/masked-view": "^0.1.10",

`error: Error: Unable to resolve module `./components/TouchableRipple` from `node_modules\react-native-paper\src\index.tsx`:

None of these files exist:
  * node_modules\react-native-paper\src\components\TouchableRipple(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
  * node_modules\react-native-paper\src\components\TouchableRipple\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
    at ModuleResolver.resolveDependency`

complete log 
`error: Error: Unable to resolve module `./components/TouchableRipple` from `node_modules\react-native-paper\src\index.tsx`:

None of these files exist:
  * node_modules\react-native-paper\src\components\TouchableRipple(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
  * node_modules\react-native-paper\src\components\TouchableRipple\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
    at ModuleResolver.resolveDependency (C:\Developement\ficha_familiar_movil\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Developement\ficha_familiar_movil\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Developement\ficha_familiar_movil\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (C:\Developement\ficha_familiar_movil\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Developement\ficha_familiar_movil\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Developement\ficha_familiar_movil\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at C:\Developement\ficha_familiar_movil\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Developement\ficha_familiar_movil\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)`

complete package 
{
  "name": "ficha_familiar_movil",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@hookform/resolvers": "^0.1.0",
    "@react-native-community/datetimepicker": "^3.0.4",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@types/react-native-vector-icons": "^6.4.5",
    "@types/react-redux": "^7.1.9",
    "axios": "^0.19.2",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-hook-form": "^6.9.6",
    "react-native": "0.63.2",
    "react-native-elements": "^2.3.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-image-picker": "^2.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-modal-datetime-picker": "^8.9.3",
    "react-native-multiple-select": "^0.5.6",
    "react-native-paper": "^4.0.1",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-screens": "^2.10.1",
    "react-native-sectioned-multi-select": "0.7.7",
    "react-native-vector-icons": "^7.1.0",
    "react-navigation": "^4.4.2",
    "react-redux": "^7.2.1",
    "realm": "^6.1.4",
    "redux": "^4.0.5",
    "redux-form": "^8.3.6",
    "redux-thunk": "^2.3.0",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@babel/core": "7.11.1",
    "@babel/runtime": "7.11.2",
    "@react-native-community/eslint-config": "1.1.0",
    "@types/jest": "^26.0.15",
    "@types/react": "^16.9.53",
    "@types/react-native": "^0.63.30",
    "@types/react-test-renderer": "^16.9.3",
    "@types/yup": "^0.29.8",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1",
    "redux-tools": "^3.2.0",
    "typescript": "^3.9.7"
  },
  "jest": {
    "preset": "react-native"
  }
}
I also tried giving it npm update and installing it newer but still :(
 Thanyou for any help

**Comment by feliperoan** [comment]
I already tried with the latest version npm update and I still have the same error
